yolo copy board def validations WIP

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -4,7 +4,7 @@ name: Validate JSONs
 on: [pull_request]
 
 jobs:
-  validate-component-definitions:
+  validate-definition-files:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -21,23 +21,41 @@ jobs:
           schema: /components/i2c/schema.json
           jsons: components/i2c/*/definition.json
 
-      - name: List Changed Component Files
-        id: changed-files
+  changed-files:
+    name: List Changed Files
+    runs-on: ubuntu-latest
+    outputs:
+      # All files that were Added, Copied, Modified, or Renamed
+      files: ${{ steps.list-changed-files.outputs.all_changed_files }}
+
+    steps:
+      - uses: actions/checkout@v3
+      - name: List Changed Board Files
+        id: list-changed-files
         uses: tj-actions/changed-files@v21
         with:
           files: components/**/*
 
-      - name: Validate Filenames
+  validate-expected-filenames:
+    name: Validate Filenames
+    runs-on: ubuntu-latest
+    needs: changed-files
+    env:
+      FILES: ${{ needs.changed-files.outputs.files }}
+
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate Only Expected Filenames
         run: |
           component_definition_regex="^components\/(pin|i2c)\/.*\/(definition\.json|image\.(png|jpe?g|gif)|animation\.gif)$"
-          exit_value=0
+          EXIT_VALUE=0
 
           for file in ${{ steps.changed-files.outputs.added_files }}; do
             if [[ $file =~ $component_definition_regex ]]; then
               echo "✅ $file"
             else
               echo "❌ $file"
-              exit_value=1
+              EXIT_VALUE=1
             fi
           done
 
@@ -46,8 +64,177 @@ jobs:
               echo "✅ $file"
             else
               echo "❌ $file"
-              exit_value=1
+              EXIT_VALUE=1
             fi
           done
 
-          exit $exit_value
+          exit $EXIT_VALUE
+
+  validate-image-extension-mimetype-agreement:
+    name: Validate Extensions Match Mimetypes
+    runs-on: ubuntu-latest
+    needs:
+      - changed-files
+      - validate-expected-filenames
+    env:
+      FILES: ${{ needs.changed-files.outputs.files }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate Image File Extension<->Mimetype Agreement
+        run: |
+          EXIT_VALUE=0
+
+          for FILE in $FILES; do
+            if [[ $FILE == */definition.json ]]; then
+              continue # non-image file
+            fi
+
+            # extract each file's mimetype and extension
+            MIME=`file -b --mime-type $FILE`
+            EXT="${FILE##*.}"
+
+            # ad-hoc check that extension matches mimetype
+            if [[ "image/$EXT" == $MIME || ($EXT == "jpg" && $MIME == "image/jpeg") || ($EXT == "svg" && ($MIME == "image/svg+xml" || $MIME == "text/xml")) ]]; then
+              # Match!
+              echo "✅ $FILE"
+
+            else
+              # Doesn't match? Give helpful report
+
+              # split the mimetype on '/'
+              IFS='/'
+              read -a SPLIT_MIME <<< "$MIME"
+              IFS=' '
+              # take the last item
+              MIME_EXT=${SPLIT_MIME[-1]}
+
+              if [[ "$MIME_EXT" == "xml" ]]; then
+                MIME_EXT="svg"
+              elif [[ "$MIME_EXT" == "jpeg" ]]; then
+                MIME_EXT="jpg"
+              fi
+
+              echo "❌ $FILE: expected .$MIME_EXT"
+
+              EXIT_VALUE=1
+            fi
+          done
+
+          if [[ $EXIT_VALUE = 1 ]]; then
+            echo "Fix these ☝️ issues by renaming each ❌ file to the indicated extension."
+          fi
+
+          exit $EXIT_VALUE
+
+  validate-image-dimensions:
+    name: Validate Image Dimensions
+    runs-on: ubuntu-latest
+    needs:
+      - changed-files
+      - validate-image-extension-mimetype-agreement
+    env:
+      FILES: ${{ needs.changed-files.outputs.files }}
+    steps:
+      - uses: actions/checkout@v3
+      - uses: mfinelli/setup-imagemagick@v1
+      - name: Validate Image Dimensions
+        run: |
+          EXIT_VALUE=0
+
+          MAX_WIDTH=800
+          MAX_HEIGHT=2000
+
+          for FILE in $FILES; do
+            if [[ $FILE == */definition.json ]]; then
+              continue # non-image file
+            fi
+
+            # use imagemagick for the width
+            WIDTH=`identify -ping -format "%w" ${FILE}[0]`
+            BAD_WIDTH=false
+            if [[ "$WIDTH" -gt "$MAX_WIDTH" ]]; then
+              EXIT_VALUE=1
+              BAD_WIDTH=true
+            fi
+
+            # use imagemagick for the height
+            HEIGHT=`identify -ping -format "%h" ${FILE}[0]`
+            BAD_HEIGHT=false
+            if [[ "$HEIGHT" -gt "$MAX_HEIGHT" ]]; then
+              EXIT_VALUE=1
+              BAD_HEIGHT=true
+            fi
+
+            if [[ $BAD_WIDTH = true || $BAD_HEIGHT = true ]]; then
+              echo "❌ $FILE  (${WIDTH}x${HEIGHT})"
+              if [[ $BAD_WIDTH = true ]]; then
+                echo "  ↔️ width must be 800 pixels or less"
+              fi
+
+              if [[ $BAD_HEIGHT = true ]]; then
+                echo "  ↕️ height must be 2000 pixels or less"
+              fi
+
+            else
+              echo "✅ $FILE  (${WIDTH}x${HEIGHT})"
+            fi
+          done
+
+          if [[ $EXIT_VALUE = 1 ]]; then
+            echo "Fix these ☝️ issues by resizing each ❌ image to fit within ${MAX_WIDTH}x${MAX_HEIGHT}."
+          fi
+
+          exit $EXIT_VALUE
+
+  validate-image-file-sizes:
+    name: Validate Image File Sizes
+    runs-on: ubuntu-latest
+    needs:
+      - changed-files
+      - validate-image-dimensions
+    env:
+      FILES: ${{ needs.changed-files.outputs.files }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate Image File Sizes
+        run: |
+          EXIT_VALUE=0
+
+          MAX_FILESIZE=$((400*1024)) # 400kb
+          MAX_ANIGIF_FILESIZE=$((1000*1024)) # 1MB
+
+          for FILE in $FILES; do
+            if [[ $FILE == */definition.json ]]; then
+              continue # non-image file
+            fi
+
+            FILESIZE=$(stat -c%s "$FILE")
+
+            if [[ $FILE == *loader.gif ]]; then
+              MAX=$MAX_ANIGIF_FILESIZE
+            else
+              MAX=$MAX_FILESIZE
+            fi
+
+            if [[ "$FILESIZE" -gt "$MAX"  ]]; then
+              EXIT_VALUE=1
+              echo "❌ $FILE ($FILESIZE)"
+
+            else
+              echo "✅ $FILE ($FILESIZE)"
+            fi
+          done
+
+          if [[ $EXIT_VALUE = 1 ]]; then
+            echo "Fix these issues ☝️ by compressing each ❌ file to be smaller than 400KB (1MB for boot-loader.gif animations). You can try:"
+            echo "- shrinking the image's dimensions (do this first if dimension validation also failed for a given file)"
+            echo "- using an image compressor"
+            echo "- exporting at lower quality settings (png or jpg)"
+            echo "- exporting a different image format:"
+            echo "  - photos are best saved as jpg"
+            echo "  - screenshots and digital images are best saved as png"
+            echo "  - svg might be efficient for images with few colors and simple shapes"
+            echo "  - gif should only be used when animation is needed (i.e. the boot-loader image)"
+          fi
+
+          exit $EXIT_VALUE
